import Head from 'next/head'
import OpenAi from '../../OpenAi.json'

export const Boss = () => {
  return (
    <>
      <Head>
        <title>{OpenAi.WebName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
